name: professional_pitch
description: A professional video pitch recording app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Camera functionality
  camera: ^0.10.5+5
  
  # Video player
  video_player: ^2.8.1
  
  # File system paths
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true